# Generated by Django 6.0.2 on 2026-03-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[(1, 'Teacher')], default='STUDENT', max_length=10),
        ),
    ]
