# Generated by Django 6.0.2 on 2026-04-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
